### ISSUE TITLE
DataLoader Error

### ISSUE THREAD

**Issue by myagmur01** [saparina/neural-ode#4]
Hi Irina, 

Thanks for this great work. 
I am having an issue with DataLoader of Pytorch, it seems giving memory error or something. Can you help how to handle this? Actually it is MNIST, loading should not matter. I decreased the batch to 1 as well, but still having the same issue.

>>>
Traceback (most recent call last):
  File "./experiments/train.py", line 103, in <module>
    train_loss_all.append(train(epoch, train_loader, model, optimizer, device))
  File "./experiments/train.py", line 43, in train
    for batch_idx, (data, target) in tqdm(enumerate(train_loader), total=len(train_loader)):
  File "/home/yagmur/anaconda3/envs/ode/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1005, in __iter__
    for obj in iterable:
  File "/home/yagmur/anaconda3/envs/ode/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 576, in __next__
    idx, batch = self._get_batch()
  File "/home/yagmur/anaconda3/envs/ode/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 553, in _get_batch
    success, data = self._try_get_batch()
  File "/home/yagmur/anaconda3/envs/ode/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 519, in _try_get_batch
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 5169, 5170) exited unexpectedly
>>>

**Comment by saparina** [comment]
Hi! Sorry about the delay with the answer. Did you try to change ```num_workers``` parameter in all DataLoaders (like [here](https://github.com/saparina/neural-ode/blob/e1107abd9e89d975a82d13d3f847faed3f30ea98/experiments/data_helper.py#L96))?
